# Generated by Django 5.0.1 on 2024-01-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_pdf_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="count_words",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pdf",
            name="num_pages",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
