# Generated by Django 5.0.1 on 2024-01-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_teachableagent_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachableagent",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
