# Generated by Django 5.0.1 on 2024-01-22 04:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_pdf_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pdf",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
