# Generated by Django 5.0.1 on 2024-01-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_pdf_created_at_pdf_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="name",
            field=models.CharField(default="a", max_length=255),
            preserve_default=False,
        ),
    ]
