# Generated by Django 5.0.1 on 2024-01-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_groupchat_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="instruction",
            field=models.TextField(blank=True, null=True),
        ),
    ]
